### ISSUE TITLE
32k Galaxy texture missing a tile

### ISSUE THREAD

**Issue by BrotherBloat** [CharonSSS/RSS-Origin#3]
The GalaxyTex_NegativeX.dds file in `RSS-Origin.GalaxyTex32k.zip` is a 100% black square.

**Comment by CharonSSS** [comment]
Yes it is. Will be fixed in next update. Thank you for mentioning this issue!

**Comment by CharonSSS** [comment]
GalaxyTex 32k in v1.1.1 release is now corrected and released, will be announced in next update

**Comment by BrotherBloat** [comment]
Thank you! :)
